
use golden_shoe;
db.dropDatabase();


db.shoes.insertMany([{
    "id": 1,
    "make": "Nike",
    "model": "Air",
    "logo_location": "images/nike_max.jpg",
    "stockLevel": "10",
    "gender": "Mens",
    "price": 10.99,
    "type": "Trainers",
    "colours": ["Black", "White", "Navy"],
    "rating": 4.5,
    "description": "The Nike Air Force 1 is a classic basketball design with a modern twist. Featuring all the elements that make this style a favourite; tough leather upper with clean cut lines, extensive stitch detail and chunky air sole unit to top off."
},
{
    "id": 2,
    "make": "Adidas",
    "model": "Gazelle",
    "logo_location": "images/adidas_gaz.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 70.99,
    "type": "Trainers",
    "colours": ["Black", "White"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
},
{
    "id": 3,
    "make": "Vans",
    "model": "Era",
    "logo_location": "images/vans.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 22.99,
    "type": "Trainers",
    "colours": ["Black", "White"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
},
{
    "id": 4,
    "make": "Adidas",
    "model": "Gazelle",
    "logo_location": "images/adidas_hanz.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 38.99,
    "type": "Trainers",
    "colours": ["Green"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
},
{
    "id": 5,
    "make": "Icon",
    "model": "London",
    "logo_location": "images/brown.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 40.99,
    "type": "Trainers",
    "colours": ["Black", "White"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
},
{
    "id": 6,
    "make": "Converse",
    "model": "Hi-top",
    "logo_location": "images/converse.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 50.99,
    "type": "Trainers",
    "colours": ["Black", "White"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
},
{
    "id": 7,
    "make": "Dr Martins",
    "model": "black",
    "logo_location": "images/dr.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 82.99,
    "type": "Trainers",
    "colours": ["Black", "White"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
},
{
    "id": 8,
    "make": "Dr Martins",
    "model": "Tartan",
    "logo_location": "images/dr2.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 95.99,
    "type": "Trainers",
    "colours": ["Black", "White"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
},
{
    "id": 9,
    "make": "Lacoste",
    "model": "wshite",
    "logo_location": "images/lacoste.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 32.99,
    "type": "Trainers",
    "colours": ["Black", "White"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
},
{
    "id": 10,
    "make": "New Balance",
    "model": "Grey",
    "logo_location": "images/new_balance.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 27.99,
    "type": "Trainers",
    "colours": ["Black", "White"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
},
{
    "id":11,
    "make": "Puma",
    "model": "Rs-0",
    "logo_location": "images/puma.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 31.99,
    "type": "Trainers",
    "colours": ["Black", "White"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
},
{
    "id": 12,
    "make": "Nike",
    "model": "Sliders",
    "logo_location": "images/sliders.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 9.99,
    "type": "Trainers",
    "colours": ["Black", "White"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
},
{
    "id": 13,
    "make": "Timberland",
    "model": "Farmer",
    "logo_location": "images/timberland.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 107.99,
    "type": "Trainers",
    "colours": ["Black", "White"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
},
{
    "id": 14,
    "make": "Skechers",
    "model": "Low",
    "logo_location": "images/skech.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 59.99,
    "type": "Trainers",
    "colours": ["Black", "White"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
},
{
    "id": 15,
    "make": "Tommy Hilfiger",
    "model": "Lightweight",
    "logo_location": "images/tommy.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 57.99,
    "type": "Trainers",
    "colours": ["Black", "White"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
},
{
    "id": 16,
    "make": "Vans",
    "model": "Skate",
    "logo_location": "images/vans2.jpg",
    "stockLevel": "5",
    "gender": "unisex",
    "price": 62.99,
    "type": "Trainers",
    "colours": ["Black", "White"],
    "rating": 4.3,
    "description": "The only way adidas can make their fan-favourite Gazelle even more iconic, is to deliver it in a slick triple black colourway. This versatile trainer is ready to take on your everyday with a premium suede upper and authentic 3-Stripe and tongue branding."
}
]

);